guild_id = 0                   # The guild id of guild the module is supposed to manage
remove_role_when_owned = false # Remove the role if the user clicks again on the button and already has the role

[messages]

[messages.test] # Name to use for the Message. Name behind the dot will be title of the Embed

title = ""       # Title of the embed
channel_id = 0   # The Channel ID where to put in the specific message 
message_id = 0   # The message id of the message to keep watch and edit for role assignment. Leave empty for automatic generation
title_url = ""   # Assigns a URL to the title
description = "" # The description of the generated embed. Can be empty
color = "FFFFFF" # The color for the embed color strip in hexadecimal. Can be empty
thumbnail = ""   # URL to an image or you can place an image in the "assets" folder of this module and use its file name with extension. Can be empty

[messages.test.author]
name = "" # Name of the author for the generated embed. Can be empty, but required for author icon and url
icon = "" # URL to an image or you can place an image in the "assets" folder of this module and use its file name with extension. Can be empty
url = ""  # URL to open when clicked on. Could be a website or anything. Can be empty

[messages.test.footer]
text = ""     # The footer of the generated embed. Can be empty but needed for footer icon_url
icon_url = "" # URL to an image or you can place an image in the "assets" folder of this module and use its file name with extension. Can be empty

[messages.test.entries]
#You can add extra entries here. They will all be seperate entries in the generated embed

[messages.test.entries.example_entry]
title = ""       # Header of the entry
role_id = 0      # Role ID to use
emoji_id = 0     # Emoji ID to use for Role Assignment. Can be int or unicode characters 
description = "" # Description for the role. Optional
